[project]
name = "viabill-analysis"
version = "0.1.0"
dependencies = [
    "pandas",
    "matplotlib",
    "pydantic",
    "jupyter"
    ]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
